version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: and
        validate:
          - do: changeset
            must_include:
              regex: src/my-protected-codeowner-code/.*
            and: null
          - do: approvals
            required:
              reviewers:
                - jrmykolyn
              message: Jesse must review this!
